---
# file: roles/blendcube/tasks/main.yml

- name: Make config directory
  file:
    path: /etc/blendcube
    state: directory
    owner: centos
    group: centos
    mode: 0755
  tags:
    - blendcube

- name: Configure nginx conf
  template:
    src: blendcube.conf.j2
    dest: /etc/nginx/conf.d/blendcube.conf
  notify: Restart Nginx
  tags:
    - blendcube

- name: Configure conf
  template:
    src: config.json.j2
    dest: /etc/blendcube/config.json
  notify: Restart BlendCube
  tags:
    - blendcube

- name: Configure logrotate conf
  template:
    src: blendcube.logrotate.j2
    dest: /etc/logrotate.d/blendcube
    owner: root
    group: root
    mode: 0644
  tags:
    - blendcube

- name: Configure systemd service
  template:
    src: blendcube.service.j2
    dest: /etc/systemd/system/blendcube.service
  tags:
    - blendcube

- name: Start app
  systemd:
    name: blendcube
    state: started
    daemon_reload: yes
    enabled: yes
  tags:
    - blendcube
