---
# file: roles/certbot/handlers/main.yml

- name: Stop nginx
  systemd:
    name: nginx
    state: stopped
  tags:
    - certbot

- name: Get SSL keys
  command: |
    certbot certonly --standalone \
      -m {{ email }} \
      --agree-tos \
      --non-interactive \
      -d {{ domain }}
  tags:
    - certbot

- name: Start nginx
  systemd:
    name: nginx
    state: started
  tags:
    - certbot
