---
# file: roles/nginx/tasks/main.yml

- name: Install nginx repository
  yum:
    name: http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
    state: present
  tags:
    - nginx

- name: Install nginx
  yum:
    name: nginx
    state: present
  tags:
    - nginx

- name: Start nginx
  systemd:
    name: nginx
    enabled: yes
    state: started
  tags:
    - nginx

- name: Delete default configuration file
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  tags:
    - nginx

- name: Configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart nginx
  tags:
    - nginx

- name: Set httpd_can_network_connect flag
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  tags:
    - nginx
