---
# file: roles/certbot/tasks/main.yml

- name: Install epel-release
  yum:
    name: epel-release
    state: present
  tags:
    - certbot

- name: Install certbot
  yum:
    name: certbot
    state: present
    enablerepo: epel
  notify:
    - Stop nginx
    - Get SSL keys
    - Start nginx
  tags:
    - certbot

- name: Check certification existence
  stat:
    path: /etc/letsencrypt/live/{{ domain }}/fullchain.pem
  register: cert_test
  changed_when: False
  tags:
    - certbot

- name: Stop nginx
  systemd:
    name: nginx
    state: stopped
  when: not cert_test.stat.exists
  tags:
    - certbot

- name: Get SSL keys
  command: |
    certbot certonly --standalone \
      -m {{ email }} \
      --agree-tos \
      --non-interactive \
      -d {{ domain }}
  when: not cert_test.stat.exists
  tags:
    - certbot

- name: Start nginx
  systemd:
    name: nginx
    state: started
  when: not cert_test.stat.exists
  tags:
    - certbot

- name: Set renew script to crontab
  cron:
    name: cerbot renew
    special_time: monthly
    job: /bin/certbot renew --post-hook "systemctl reload nginx"
  tags:
    - certbot
