name: Build

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out
      uses: actions/checkout@v1

    - name: Build binary
      run: make build

    - name: Build RPM
      uses: ./.github/actions/rpmbuild
