name: Build

on:
  push:
    tags:
      - "*"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      APP: blendcube
    steps:

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Check out
        uses: actions/checkout@v1

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d'/' -f3)

      - name: Build binary
        run: make build

      - name: Make Config
        run: |
          cat config.json.example |\
            jq '.log.file_path="/var/log/${{ env.APP }}/${{ env.APP }}.log"' |\
            jq '.model.file_path="/etc/${{ env.APP }}/cube.gltf"' |\
            jq '.model.binary_file_path="/etc/${{ env.APP }}/cube.glb"' \
            > config.json

      - name: Archive Source
        run: |
          mkdir -p ${{ env.APP }}-${{ steps.get_version.outputs.VERSION }} SOURCES
          cp ${{ env.APP }} \
            config.json \
            config/cube.gltf \
            config/cube.glb \
            config/service \
            config/logrotate \
            ${{ env.APP }}-${{ steps.get_version.outputs.VERSION }}/
          tar czf \
            SOURCES/${{ env.APP }}-${{ steps.get_version.outputs.VERSION }}.tar.gz \
            ${{ env.APP }}-${{ steps.get_version.outputs.VERSION }}/

      - name: Build RPM
        uses: ./.github/actions/rpmbuild

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.APP }}-${{ steps.get_version.outputs.VERSION }}-1.x86_64.rpm
          path: ./RPMS/x86_64/${{ env.APP }}-${{ steps.get_version.outputs.VERSION }}-1.x86_64.rpm
