name: Build

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out
      uses: actions/checkout@v1

    - name: Build binary
      run: make build

    - name: Make Config
      run: |
        cat config.json.example |\
          jq '.log.file_path="/var/log/blendcube/blendcube.log"' |\
          jq '.model.file_path="/etc/blendcube/model/cube.gltf"' |\
          jq '.model.binary_file_path="/etc/blendcube/model/cube.glb"' \
          > config.json

    - name: Archive Source
      run: |
        mkdir -p dist
        cp blendcube dist/
        cp config.json dist/
        cp model/cube.gltf dist/
        cp model/cube.glb dist/
        tar czf dist.tar.gz dist/

    - name: Build RPM
      uses: ./.github/actions/rpmbuild
